exclude: ^setup.py$

repos:
  ###################
  #    FORMATTER    #
  ###################
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: fix-encoding-pragma
        args: [--remove]
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/python/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4 # Use the sha or tag you want to point at
    hooks:
      - id: prettier

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.2.0
    hooks:
      - id: setup-cfg-fmt
        args: [--include-version-classifiers]

  ###################
  #     LINTER      #
  ###################
  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa
        additional_dependencies: [flake8-docstrings, darglint==1.8.1]

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        name: "flake8 lint code"
        additional_dependencies: [flake8-pyi, flake8-comprehensions]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        exclude: "docs"
        additional_dependencies: [types-all, pydantic]

  ###################
  #   LINTER DOCS   #
  ###################

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        alias: flake8-docs
        args:
          - "--select=D,DAR"
        name: "flake8 lint docstrings"
        exclude: "docs|tests?/"
        additional_dependencies: [flake8-docstrings, darglint==1.8.1]

  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [-v, --config=pyproject.toml, "pyglotaran_model_language"]
        pass_filenames: false

  - repo: https://github.com/rstcheck/rstcheck
    rev: "v6.1.0"
    hooks:
      - id: rstcheck
        additional_dependencies: [sphinx]
        exclude: "^docs/_templates"

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: rst-backticks
      - id: python-check-blanket-noqa
        exclude: "docs|tests?"
      - id: python-check-blanket-type-ignore
        exclude: "docs|tests?"
      - id: python-use-type-annotations
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        types: [file]
        types_or: [python, markdown, rst, jupyter]
        args: [-L nnumber]
